DB_PASSWORD: ""
DB_USERNAME: "postgres"
DB_HOST: "localhost"
DB_PORT: "4040"
DB_NAME_DEVELOPMENT: "code_legends_development"
DB_NAME_TEST: "code_legends_test"
DB_NAME_PRODUCTION: "code_legends_production"
