default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.credentials.db[:db_password] %>
  password: <%= Rails.application.credentials.db[:db_username] %>
  host: localhost

development:
  <<: *default
  database: code_legends_development

test:
  <<: *default
  database: code_legends_test

production:
  <<: *default
  database: code_legends
  username: <%= Rails.application.credentials.db[:db_username] %>
  password: <%= Rails.application.credentials.db[:db_password] %>
